LESSON 2

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [85]:
#import numpy library
import numpy as np

# create a nested list containing values from 1 to 10(1 to 10 is my chosen range from the given values of 1-100), then it is repeated 10 times
nested_list = [[i for i in range(1, 11)] for _ in range(10)]

# convert the nested list to a numpy array
A = np.array(nested_list)

# access the shape property of the ndarray object A
shape_of_A = A.shape

# find the max value using max() method
max_of_A = A.max()

# find the max value using np.max() function
max_of_A_using_np = np.max(A)

# display
print(A)
print("\nShape of A:", shape_of_A)
print("\nMaximum value in A:", max_of_A)
print("\nMaximum value in A using np.max:", max_of_A_using_np)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]

Shape of A: (10, 10)

Maximum value in A: 10

Maximum value in A using np.max: 10


B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [46]:
#import numpy library
import numpy as np

# this creates a 5x5 array of only ones
ones_array = np.ones((5, 5), dtype=int)

# Check shape, size, and number of dimensions

# itretrieves the shape of the array and assigns it to shape
shape = ones_array.shape

# it retrieves the total number of elements in the array and assigns it to  size
size = ones_array.size

# it retrieves the number of dimensions of the array and assigns it to ndim
ndim = ones_array.ndim


# display
print(ones_array)
print("\nShape:", shape)
print("\nSize:", size)
print("\nNumber of Dimensions:", ndim)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape: (5, 5)

Size: 25

Number of Dimensions: 2


C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [86]:
#import numpy library
import numpy as np

# create an array of values from -5 to +5
values = np.array(range(-5, 6))

# this multiplies each value by 2
result_array = values * 2

# display
print("Output:", result_array)

Output: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [89]:
#import numpy library
import numpy as np

# it starts from 2 and ends at 62 to have 30 values with an increment of 2
# actual result before multiplication [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]
array = np.arange(2, 62, 2)

# multiply the resulting array by 3
array *= 3

# disaply
print(array)

[  6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102 108
 114 120 126 132 138 144 150 156 162 168 174 180]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [91]:
#import numpy library
import numpy as np

# creates a four-dimensional array of random integers between 0 and 12. ( 2 layers, 3 rows, 4 columns, 5 elements)
four_d_array = np.random.randint(0, 13, size=(2, 3, 4, 5))

# finding the max for each dimension
max = np.max(four_d_array, axis=(0, 1, 2, 3))

# it multiplies each array element by 4
multiplied_array = four_d_array * 4

#display the four-dimensional array | getting the dimensions, shape, size, and max number for each dimension
print(multiplied_array)
print("\nDimensions:", multiplied_array.ndim)
print("\nShape:", multiplied_array.shape)
print("\nSize:", multiplied_array.size)
print("\nMaximum number for each dimension:", max)

[[[[36 40 44 12 12]
   [28 32 16 48  0]
   [ 0  8  0 28 48]
   [12 36 28  0 24]]

  [[ 8 24  4 40 36]
   [28 28 24 20 24]
   [ 0 20 24 36 40]
   [ 0 40 36 44 32]]

  [[20 48 28 48 16]
   [ 4 48 44 48 12]
   [20  0 20  0 32]
   [36 36 44 12 32]]]


 [[[24  8  4 36  4]
   [12 44 44 28  4]
   [16 44  0  4  8]
   [28 32  4 44 48]]

  [[12 36 40 36 16]
   [ 8 40 16  0 32]
   [24 40  4 16  8]
   [ 8 24 20 44 16]]

  [[ 8 48 20 44 44]
   [12 40  4 12 44]
   [20 32 28  4 40]
   [16 16 12 20 36]]]]

Dimensions: 4

Shape: (2, 3, 4, 5)

Size: 120

Maximum number for each dimension: 12
